# Generated by Django 4.0.6 on 2022-09-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0011_positions_pnl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='monthly_expiry',
        ),
    ]
