# Generated by Django 4.0.6 on 2022-09-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0012_remove_strategy_monthly_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='time_in',
            field=models.DateTimeField(default='_'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='time_out',
            field=models.DateTimeField(default='_'),
        ),
    ]
