# Generated by Django 3.1.7 on 2022-10-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0013_alter_positions_time_in_alter_positions_time_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='bot',
        ),
        migrations.AddField(
            model_name='strategy',
            name='buy',
            field=models.CharField(default='off', max_length=4),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sell',
            field=models.CharField(default='off', max_length=4),
        ),
    ]
