# Generated by Django 3.1.7 on 2022-10-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0014_auto_20221008_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='lots',
        ),
        migrations.AddField(
            model_name='strategy',
            name='amount_invested',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='strategy',
            name='position_increase',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='strategy',
            name='range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='strategy',
            name='stoploss',
            field=models.IntegerField(default=1),
        ),
    ]
