# Generated by Django 3.1.7 on 2022-10-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0016_auto_20221008_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategy',
            old_name='paper',
            new_name='stop',
        ),
    ]
