# Generated by Django 3.1.7 on 2022-10-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0019_auto_20221009_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='position_increase',
            field=models.FloatField(default=0),
        ),
    ]
