# Generated by Django 3.1.7 on 2022-10-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0021_stop_symboll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='symbol',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='stop_symboll',
            name='symbol',
            field=models.DateTimeField(default='_'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='username',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
