# Generated by Django 3.1.7 on 2022-10-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0023_auto_20221017_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='max_stoploss',
            field=models.FloatField(default=0),
        ),
    ]
